# Generated by Django 4.2.6 on 2023-11-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_testresult_is_passed_testresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
